### ISSUE TITLE
how to update it to last version?

### ISSUE THREAD

**Issue by tvvocold** [worldline/openshift-lets-chat#2]

**Comment by maxired** [comment]
Hi,

You can use the master of https://github.com/maxired/lets-chat, which is based on version 0.3.3
In case of failure, you might want to use a medium gear or a scalable app. 
Since there is lots of dependencies, you might also need to first create your app with no code, and then push it.

**Comment by maxired** [comment]
Since https://github.com/sdelements/lets-chat/pull/263 has been closed, you should be able to use directly https://github.com/sdelements/lets-chat

**Comment by tvvocold** [comment]
hi there,
Thank you very much!
So i try ur commit but got a [push loop](http://p.fdzh.org/paste/epg9J5kO)
here is [my step](http://p.fdzh.org/paste/gd4Bvl1G) and i had $cp settings.yml.sample settings.yml before push.

Why and how to fix?(or if this is a quota limit ,can i create another gear to run mongodb?)

**Comment by maxired** [comment]
Hi,

from what i see, there is not loop. I think you are mixing
preinstall oauth-sign@0.6.0
and
postinstall oauth-sign@0.6.0

I got only one things to way: wait and see ;).
I just reproduced your step, and got nearl 11K lines before the desired
"preparing apps for deployment" ;)

Moreover, I would advice you to use a bigger gear,
```
rhc app-create letschat nodejs-0.10 mongodb-2.4 -g medium
```

**Comment by maxired** [comment]
Hi,

from what i see, there is not loop. I think you are mixing

``` bash
preinstall oauth-sign@0.6.0
```

and

``` bash
postinstall oauth-sign@0.6.0
```

I got only one things to way: wait and see ;).
I just reproduced your step, and got nearl 11K lines before the desired
"preparing apps for deployment" ;)

Moreover, I would advice you to use a bigger gear,

``` bash
rhc app-create letschat nodejs-0.10 mongodb-2.4 -g medium
```

**Comment by tvvocold** [comment]
Wow,11K, that's too much dependencies, i shall try it some time.Thx anyway!
